### ISSUE TITLE
Gerrit support

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/bitrise-webhooks#13]
It'd be nice if bitrise supported triggering builds from Gerrit.

- https://github.com/sonyxperiadev/gerrit-events

**Comment by viktorbenei** [comment]
Awesome idea!
Feel free to create a PR if you have the time ;)

**Comment by bootstraponline** [comment]
I don't know Go that well but it looks like it'd be possible:

- https://github.com/andygrunwald/go-gerrit
- https://github.com/talios/gowest/blob/f04a54811e2d8bccafe04983e8362e975e35c7c3/gerrit.go#L89

I think a lot of the required hooks on the bitrise side are missing. There's no API to query build status or to cancel builds when a new patchset is uploaded.

**Comment by bootstraponline** [comment]
I don't use Gerrit anymore. 😄
