### ISSUE TITLE
Pass Slack webhook POST data to Bitrise

### ISSUE THREAD

**Issue by chrisfullscreen** [bitrise-io/bitrise-webhooks#15]
Is there anyway we can pass the POST data from Slack into bitrise (e.x. user_id, user_name, etc...) so that we can add some additional customization in the workflow such as adding a message or record on who initiated the build?

**Comment by viktorbenei** [comment]
You should use the custom environment variables for that https://github.com/bitrise-io/bitrise-webhooks#slack---setup--usage

**Comment by chrisfullscreen** [comment]
Do the variables that comes from Slack (not specified by user when triggering the webhook) get passed onto the build webhook?   It looks like these are the values that Slack will send along when an outgoing webhook is invoked:

> token=XXXXXXXXXXXXXXXXXX
> team_id=T0001
> team_domain=example
> channel_id=C2147483705
> channel_name=test
> timestamp=1355517523.000005
> user_id=U2147483697
> user_name=Steve
> text=googlebot: What is the air-speed velocity of an unladen swallow?
> trigger_word=googlebot:

For example, we would like to find out which Slack user initiated the build automatically, instead of asking user to type in their name manually through an environment variable, the Bitrise Slack hook will get this info from Slack and pass it along.  Is this possible?

**Comment by viktorbenei** [comment]
Not implemented yet, but feel free to send a PR with the implementation if you want to.

P.S.: you have to expose any custom info as environment variables, the Build Trigger API does not support any other custom data parameter, only environment variables (as that will be the form of how data is exposed for the build anyway).
