### ISSUE TITLE
Use case with 2 workflows targeting the same repository

### ISSUE THREAD

**Issue by callmephilip** [bitrise-io/bitrise-webhooks#18]
I have a question regarding a particular use case we have with 2 workflows targeting the same repository:

Workflow 1 is an iOS build
Workflow 2 is an Android build 

Both workflows update certain artifacts in the target repository and push the updates back to the github repo. Both workflows include a special message in the commit message for the changes to artifacts to instruct build process to skip (to prevent recursive builds). The issue that is as workflow 1 completes in the middle of workflow 2 and pushes the commit message, Bitrise puts workflow 2 on hold and it then resumes and finds a "skip ci" message in the latest commit and hence does not proceed with the full deployment.

My question is whether there's a setting for Bitrise that I could use to prevent build from being put on hold? Or is there a better way to accomplish this without coming up with custom skip messages for different platforms?

**Comment by viktorbenei** [comment]
> Both workflows update certain artifacts in the target repository and push the updates back to the github repo.

You shouldn't do this, you should store artifacts in deploy/artifact services, if possible

For skip ci functionality I guess this will help https://github.com/bitrise-io/bitrise-webhooks/pull/8 - ;)

**Comment by callmephilip** [comment]
what would be an example of such service. storing build numbers in a github repository is extremely convenient as it serves as the single source of truth for the whole team

**Comment by callmephilip** [comment]
Just to clarify, once #8 has landed, builds will not be suspended on commits with skip-ci flags, will they?

**Comment by viktorbenei** [comment]
Correct, those builds will be ignored completely - no build will be created at all

**Comment by callmephilip** [comment]
Awesome. I think this will resolve the issue I am having.

**Comment by viktorbenei** [comment]
Will be deployed real soon! ;)
