### ISSUE TITLE
[feature] - allow a string in the commit message to skip the build

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-webhooks#2]
Usually this is `[ci skip]` or `[skip ci]` - preferably both should be allowed.

Implementation should be in the common code, around https://github.com/bitrise-io/bitrise-webhooks/blob/master/service/hook/endpoint.go#L175

**Comment by viktorbenei** [comment]
In in production! ;)

**Comment by incanus** [comment]
I am not seeing this work and wondering why. 

See this PR, where we are removing our own handling of this and testing yours: https://github.com/mapbox/mapbox-gl-native/pull/6525

Specifically the lone commit https://github.com/mapbox/mapbox-gl-native/pull/6525/commits/e6bd16dc8e1a72046cccc9a2a13ff6adee3c125d which, as of this writing, is still running the last Bitrise jobs 😦

**Comment by viktorbenei** [comment]
In case of PR you have to include it in the PR's description / title, as that's what is treated as the commit message - you can see it on Bitrise.io build list. 

Also only the head commit counts as noted in the docs/devcenter

**Comment by viktorbenei** [comment]
See the commit message implementation here https://github.com/bitrise-io/bitrise-webhooks/blob/master/service/hook/github/github.go#L132

**Comment by incanus** [comment]
Ok, that's helpful. The doc [here](https://bitrise-io.github.io/devcenter/tips-and-tricks/skip-a-build/) is confusing because of this section: 

<img width="251" alt="screen shot 2016-09-30 at 10 25 32 am" src="https://cloud.githubusercontent.com/assets/17722/19000596/3e37542e-86f8-11e6-8fa1-9e1c976bb718.png">

There should probably be a clarification about PRs.

**Comment by viktorbenei** [comment]
I agree, or maybe we could compose the commit massage from the PR text and the head commit.. Wdyt?

**Comment by incanus** [comment]
I like that—allows the option of skipping for the whole PR as well as just individual commits (`HEAD`, at least, which is how the feature stands now).

**Comment by viktorbenei** [comment]
@incanus checked the webhook API, and I now remember why the "commit message" of a Pull Request build does not include the HEAD commit's message: because it's not in the webhook, at least not directly.

A Pull Request is actually a "temporary" commit (and branch) on GitHub, which is removed after you close the pull request (at least you won't be able to git clone the related temporary branch after the PR close), and indeed the PR's title and body is sent as the "commit title & body" in the webhook.

The webhook includes the head commit's SHA, but that's all, no other information about the commit, only about the Pull Request. Only the code push events include the commit's actual infos.

Unfortunately right now it's a bit out of scope to send additional requests for a PR object like this to gather e.g. the commit message of the head commit in the PR.

We'll definitely do one fix though, to start a build if the PR is changed, so that e.g. if you initially include `[skip ci]` in the PR's title of description it'll skip all builds, but once you remove it from the title/body it'll build the last commit right away, and any other commit after the `[skip ci]` removal from the PR title/body.

Would that work?

**Comment by viktorbenei** [comment]
Alternatively of course you can build the Code Push events instead of the PR ones, but that will test the commit as-it-is, not in a pre-merged form (which is the temporary PR commit & branch).

**Comment by viktorbenei** [comment]
Related PR: https://github.com/bitrise-io/bitrise-webhooks/pull/21/files

**Comment by viktorbenei** [comment]
Related DevCenter update https://github.com/bitrise-io/devcenter/pull/40/files
