### ISSUE TITLE
Add support for Tag triggers to the GOGS handler

### ISSUE THREAD

**Issue by crrobinson14** [bitrise-io/bitrise-webhooks#30]
See https://github.com/bitrise-io/bitrise-webhooks/pull/3#issuecomment-253995404.

**Comment by viktorbenei** [comment]
Awesome, thank you! (assigned ;))

**Comment by viktorbenei** [comment]
@crrobinson14 did you have the time to check this? If not that's not an issue either, but in that case we'd create a Feature Request for this
