### ISSUE TITLE
Add support for Microsoft Teams

### ISSUE THREAD

**Issue by a11n** [bitrise-io/bitrise-webhooks#41]
Microsoft recently released a *Slack competitor* called Microsoft teams.

It already features a couple of *connectors* to TravisCI, CircleCI and even Jenkins. A Bitrise integration would be perfect.

Integration works via web hooks:
https://dev.outlook.com/Connectors/Reference

**Comment by viktorbenei** [comment]
Thanks for the feature request! If you have the time, feel free to send us a PR - you should find every required detail in the README

**Comment by viktorbenei** [comment]
This feature request was migrated to: https://discuss.bitrise.io/t/add-microsoft-team-slack-alternative-webhook-support/223

**Comment by ggrana** [comment]
Anything new about that?

**Comment by viktorbenei** [comment]
@ggrana feel free to send a PR or vote on the feature request! ;)

**Comment by ggrana** [comment]
Nop, it was this that I was needing, I will take a look on it later today. Huge thanks!

**Comment by viktorbenei** [comment]
Glad to hear @ggrana ! ;)

**Comment by ahmetcj4** [comment]
Hi @viktorbenei, we were using slack to trigger bitrise builds. Now we want to switch MS Teams. Is there any way to trigger bitrise.io builds from MS Teams?
