### ISSUE TITLE
BitBucket Server: No X-Attempt-Number Header found

### ISSUE THREAD

**Issue by majodev** [bitrise-io/bitrise-webhooks#65]
Hi,

Looks like the [BitBucket Event Payloads](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html) documentation is not completely accurate for BitBucket Server (non Cloud). The `X-Attempt-Number` is actually never sent. Would it be possible to apply a default value instead of an error [here](https://github.com/bitrise-io/bitrise-webhooks/blob/e244cb1707ba4b4e065045170ae0c15e4950c4a0/service/hook/bitbucketv2/bitbucketv2.go#L123)?

BitBucket Server Version: v5.5.1 (latest).

<img width="807" alt="bildschirmfoto 2017-11-17 um 10 34 48" src="https://user-images.githubusercontent.com/2149883/32940614-6d48a13e-cb83-11e7-965b-24ae3f92638f.png">

**Comment by viktorbenei** [comment]
We don't support self hosted Bitbucket Server right now. Are you sure that this is the only difference between Bitbucket Server's webhook format & Bitbucket.org / Cloud's? Last time we checked the difference was quite significant.

In any case, PRs are always welcome - you can find the development readme section at https://github.com/bitrise-io/bitrise-webhooks#how-to-compile--run-the-server

You can run this server on your own Mac/PC or even deploy it to a free Heroku dyno :)

If you'd have any questions just let us know! ;)

**Comment by majodev** [comment]
As far as I can tell from the payload, it's the *only* difference.

WebHooks v2 API Support just landed recently in [BitBucket Server v5.4](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-release-notes-872139866.html) and should normally work the same way as in their Cloud solution.

**Comment by viktorbenei** [comment]
Ahh, I didn't know that Bitbucket Server now supports the Bitbucket v2 API! Thanks for the heads up! ;)

I'll add this to our internal tracker, but if you'd have some time in the meantime feel free to send us a PR, it'd be very much welcome! ;)

**Comment by viktorbenei** [comment]
Released in https://github.com/bitrise-io/bitrise-webhooks/releases/tag/1.1.37

Please let us know if this indeed fixes the Bitbucket Server webhook processing issue, and thank you for reporting! :)
