### ISSUE TITLE
New Bitbucket Server branches don't trigger builds

### ISSUE THREAD

**Issue by copini** [bitrise-io/bitrise-webhooks#69]
When pushing a new branch to a Bitbucket Server repository, the `changes` type in the payload is `ADD`.
Currently, the Bitbucket Server hook only supports the `UPDATE` change type for branches. When the change type is `ADD`, it assumes the ref should be a tag (see [bitbucketserver.go](https://github.com/bitrise-io/bitrise-webhooks/blob/master/service/hook/bitbucketserver/bitbucketserver.go#L160-L161)) and therefore fails with the following error:

> Failed to transform the webhook: 'changes' specified in the webhook, but none can be transformed into a build. Collected errors: [Ref was not a type=TAG. Type was: BRANCH]

This means we have to push an extra commit after pushing a new branch, just to trigger a build in Bitrise.
Could this be fixed?

**Comment by viktorbenei** [comment]
Hi @copini ,

Thanks for the feature request!

Not sure when we can work on this, but pull requests are always welcome! ;)

**Comment by viktorbenei** [comment]
Note: the current Bitbucket Server implementation was submitted by @ChrisTitos - not sure why this was left out, he might know more about that.

**Comment by copini** [comment]
Szia @viktorbenei!
I'll see if I can make some time to cook up a pull request in the next week. I was not sure how to test it, but now I see the instructions in your readme are pretty clear :)

**Comment by viktorbenei** [comment]
If you'd have any questions or if we can help with anything just let us know @copini ! :)

**Comment by copini** [comment]
Köszi! I've created a pull request.
The only thing I had to figure out myself was how to run the test (`go test ./service/hook/bitbucketserver`), maybe that's something you could include in the readme ;-)

**Comment by viktorbenei** [comment]
Got it and glad to hear! I'll schedule a README update for next week - of course PRs for that are also welcome :)

**Comment by viktorbenei** [comment]
@copini related PR: https://github.com/bitrise-io/bitrise-webhooks/pull/71

I'll merge that, but feel free to comment there if it's not clear enough and I'll open a new PR ;)

**Comment by viktorbenei** [comment]
And of course thanks for the feedback @copini ! :)

**Comment by copini** [comment]
It's perfect, thanks!
