### ISSUE TITLE
Add support for Discord

### ISSUE THREAD

**Issue by monolithic-adam** [bitrise-io/bitrise-webhooks#78]
Not sure if this is the right format or not but it would be great to have a webhook for Discord.

**Comment by bitce** [comment]
Thanks @monolithic-adam !

Would you consider creating a [feature request](https://discuss.bitrise.io/c/feature-request) about this? :) This way other users can vote for it and it helps us keep track of what would you guys like to see implemented.

**Comment by monolithic-adam** [comment]
@bitce Yeah no problem I will move this over there. Should I close the issue?

**Comment by bitce** [comment]
Thanks! You may do so, I'm just gonna reference the [thread here](https://discuss.bitrise.io/t/add-support-for-discord/6144), so anyone who stumbles here can find it :)

**Comment by monolithic-adam** [comment]
Thanks I hope it gains some traction!
