### ISSUE TITLE
PR triggered builds from Bitbucket are failing

### ISSUE THREAD

**Issue by mjholgate** [bitrise-io/bitrise-webhooks#87]
The webhooks for "PR changed" from Bitbucket seem to be failing to trigger builds in Bitrise now.

We're getting the following error:

`"error": "Failed to transform the webhook: Failed to parse request body as JSON: json: cannot unmarshal object into Go struct field PullRequestInfoModel.author of type string"
`

We believe this might be related to https://github.com/bitrise-io/bitrise-webhooks/pull/86

**Comment by tamasbazs** [comment]
Hi @mjholgate 
We are really sorry for the inconvenience caused by this issue 😞Our website team is looking into it and there should be a fix out soon!

**Comment by mjholgate** [comment]
No worries at all! thanks @tamasbazs !

**Comment by tamasbazs** [comment]
Hi @mjholgate 
The website team just deployed a fix and according to our testing the issue should be gone now. Could you please check and let me know if everything is going fine for you as well? 🤓

**Comment by mjholgate** [comment]
@tamasbazs that seems to have fixed it - thanks very much for the quick fix :)

**Comment by tamasbazs** [comment]
@mjholgate Perfect, thanks so much for confirming ☺️ and again, sorry for the inconvenience this caused you and your team!
